---
# Version
elasticsearch_version: 8.15.0
kibana_version: 8.15.0
logstash_version: 8.15.0
elastic_agent_version: 8.15.0
filebeat_version: 8.15.0
metricbeat_version: 8.15.0
packetbeat_version: 8.15.0
auditbeat_version: 8.15.0
heartbeat_version: 8.15.0

# Elasticsearch
elasticsearch_username: elastic
elasticsearch_password: thanos
elasticsearch_jvm: 1g
elasticsearch_cluster_name: marvel
elasticsearch_port: 9200
