---
# Version
elasticsearch_version: 8.15.3
kibana_version: 8.15.3
logstash_version: 8.15.3
fleet_server_version: 8.15.3
filebeat_version: 8.15.3
metricbeat_version: 8.15.3
packetbeat_version: 8.15.3
auditbeat_version: 8.15.3
heartbeat_version: 8.15.3

# Elasticsearch
elasticsearch_username: elastic
elasticsearch_password: thanos
elasticsearch_jvm: 512m
elasticsearch_cluster_name: marvel
elasticsearch_port: 9200
