---
- name: Create file in order to get idempotency
  ansible.builtin.file:
    path: "{{ fleet_server_idempotency_path }}"
    state: touch
    modification_time: preserve
    access_time: preserve
    owner: root
    group: root
    mode: '0600'
