---
# handlers file for logstash
- name: Restart logstash service
  ansible.builtin.service:
    name: logstash
    state: restarted

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true
