---
# defaults file for kibana
kibana_version: 8.19.0
kibana_elasticsearch_username: "{{ elasticsearch_username }}"
kibana_elasticsearch_password: "{{ elasticsearch_password }}"
kibana_elasticsearch_port: "{{ elasticsearch_port }}"
kibana_username: kibana_system
kibana_password: SBoAsENHaNIU
kibana_certificate_ca: ca.pem
