---
# tasks file for requirements
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - bash-completion
