---
# tasks file for elasticsearch
- name: Replace elasticsearch.yml
  ansible.builtin.template:
    src: elasticsearch.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  notify:
    - Restart elasticsearch

- name: Replace jvm.options
  ansible.builtin.template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
  notify:
    - Restart elasticsearch

- name: Set elastic username password
  ansible.builtin.expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-keystore add bootstrap.password
    responses:
      "Enter value for bootstrap.password:": "{{ elasticsearch_password }}"
    creates: /var/lib/elasticsearch/ansible-idempotency

- name: Create certificates directory
  ansible.builtin.file:
    path: /etc/elasticsearch/certificates
    state: directory
    owner: elasticsearch
    group: root
  notify:
    - Restart elasticsearch

- name: Copy elasticsearch certificates
  ansible.builtin.copy:
    src: "certificates/{{ item }}"
    dest: "/etc/elasticsearch/certificates/{{ item }}"
    owner: root
    group: elasticsearch
  with_items:
  - ca.pem
  - elasticsearch.key
  - elasticsearch.pem
  notify:
    - Restart elasticsearch

- name: Flush handlers
  meta: flush_handlers

- name: Check status
  ansible.builtin.uri:
    url: "https://localhost:9200/_cluster/health"
    method: GET
    user: "{{ elasticsearch_username }}"
    password: "{{ elasticsearch_password }}"
    force_basic_auth: yes
    validate_certs: no
  until: "response.status == 200"
  retries: 20
  delay: 15
  register: response

- name: Print information from the previous task
  ansible.builtin.debug:
    var: response
