---
- name: Install Elasticsearch
  ansible.builtin.apt:
    deb: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-amd64.deb"
    state: present

- name: Enable elasticsearch service
  ansible.builtin.service:
    name: elasticsearch
    enabled: true
