# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Configure VM
    config.vm.box = "ubuntu/focal64"
    config.ssh.insert_key = true
    config.vm.network "public_network"

    # Configure provisioning
    config.vm.provision "file", source: "provision", destination: "/tmp"
    config.vm.provision "shell", path: "bootstrap.sh"

    # Configure network ports
    config.vm.network "forwarded_port", host: 9200, guest: 9200 # Elasticsearch (http)
    config.vm.network "forwarded_port", host: 9300, guest: 9300 # Elasticsearch (transport)
    config.vm.network "forwarded_port", host: 5601, guest: 5601 # Kibana
    config.vm.network "forwarded_port", host: 5044, guest: 5044 # Logstash

    # Configure Virtualbox
    config.vm.provider "virtualbox" do |vb, override|
        vb.cpus = 1
        vb.memory = 4096
        vb.gui = false
        vb.name = "elastic7x"
    end

end
