# Kibana's port
server.port: 5601

# Specifies the address to which the Kibana server will bind
server.host: "0.0.0.0"

# Kibana Public Url
server.publicBaseUrl: "https://localhost:5601"
server.ssl.enabled: true
server.ssl.certificate: /etc/kibana/certificates/kibana.pem
server.ssl.key: /etc/kibana/certificates/kibana.key

# Elasticsearch Nodes
elasticsearch.hosts: "https://localhost:9200"
elasticsearch.username: "kibana"
elasticsearch.password: "kIberoglatHe"
elasticsearch.ssl.verificationMode: certificate
elasticsearch.ssl.certificateAuthorities: "/etc/kibana/certificates/ca.pem"

# Encryption Keys
xpack.security.encryptionKey: "ovswhfannlajtgvvjewqwgulywdbpudq"
xpack.reporting.encryptionKey: "mevhrpewrtunoakriahdyzowlqlvhjou"
xpack.encryptedSavedObjects.encryptionKey: "ubadnnhnuvgyrxveohfgyxpxokbkdwge"

# Security
xpack.security.secureCookies: true

# Reporting
xpack.reporting.enabled: true
xpack.reporting.csv.enablePanelActionDownload: true
xpack.reporting.capture.browser.chromium.disableSandbox: false